# Generated by Django 6.0.4 on 2026-04-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryLook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('evening', 'איפור ערב | مكياج سهرة'), ('bridal', 'איפור כלה | مكياج عروس')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='core.gallerylook')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
