# Generated by Django 6.0.4 on 2026-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('evening', 'Evening Makeup | مكياج سهرة'), ('bridal', 'Bridal Makeup | مكياج عروس')], max_length=20),
        ),
    ]
